HOST = '0.0.0.0'
PORT = 9577

SQLALCHEMY_DATABASE_URI = 'mysql://root:***@localhost/quiz'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_POOL_SIZE = 100
SQLALCHEMY_POOL_RECYCLE = 3600

DEBUG = False

SECRET_KEY = 'b++d\x04~\xce\xf3\xb7#\xf3\xe9$H\xd9\x1c'
